import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "../components/QueryProvider";
import { MainLayoutProvider } from "../components/context/LayoutContext";
import { poppins } from "../fonts/font";
import { ThemeProvider } from "@/components/ThemeProvider";
import AuthHolder from "@/components/AuthHolder";
import { DashboardProvider } from "@/components/context/Dashboardprovider";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import AuthProvider from "@/components/AuthProvider";
import { PrimeReactProvider } from "primereact/api";
import "primereact/resources/themes/lara-light-indigo/theme.css";
import "primeicons/primeicons.css";
import ReduxProvider from "@/components/store/reduxProvider";

export const metadata: Metadata = {
  title: "Enelob - Dashboard",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.className}`}>
        <ReduxProvider >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <AuthHolder session={session}>
            <AuthProvider>
              <PrimeReactProvider>
                <DashboardProvider>
                  <QueryProvider>
                    <MainLayoutProvider>{children}</MainLayoutProvider>
                  </QueryProvider>
                </DashboardProvider>
              </PrimeReactProvider>
            </AuthProvider>
          </AuthHolder>
        </ThemeProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
